myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('requestbox.urls'))
]

requestbox/urls.py
from django.urls import path
from . import views

app_name = 'requestbox'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('req/', views.AddView.as_view(), name='req'),
    path('mypage/', views.Mypage.as_view(), name='mypage'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

requestbox/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Req(models.Model):
    chara_name = models.CharField('キャラ名', max_length=20)
    title = models.CharField('作品名', max_length=30)

    def __str__(self):
        return self.chara_name

requestbox/forms.py
from django import forms
from .models import Req

class ReqCreateForm(forms.ModelForm):

    class Meta:
        model = Req
        fields = '__all__'

requestbox/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ReqCreateForm
from .models import Req
# Create your views here.


class IndexView(generic.TemplateView):
    template_name = 'requestbox/top.html'

class AddView(generic.CreateView):
    model = Req
    form_class = ReqCreateForm
    success_url = reverse_lazy('requestbox:index')

class Mypage(LoginRequiredMixin, generic.ListView):
    model = Req
    login_url = '/admin/'
    paginate_by = 10

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Req
    success_url = reverse_lazy('requestbox:mypage')

requestbox/templates/requestbox/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>request page</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <div class='container'>
    {% block content %}
    {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

requestbox/templates/requestbox/req_confirm_delete.html
{% extends 'requestbox/base.html' %}

{% block content %}
<form action="" method="POST">
  {{ req.title }}
<p>こちらのページを削除します</p>
<button type="submit" class="btn btn-dark">削除</button>
{% csrf_token %}
</form>
{% endblock %}

requestbox/templates/requestbox/req_form.html
{% extends 'requestbox/base.html' %}

{% block content %}

<h2>Request page</h2>

<form action="" method="POST">
{{ form.as_p }}

<button type="submit" class="btn btn-dark">送信</button>

<a href="{% url 'requestbox:index' %}">
<button type="button" class="btn btn-dark">戻る</button>
</a>

{% csrf_token %}
</form>


{% endblock %}

requestbox/templates/requestbox/req_list.html
{% extends 'requestbox/base.html' %}

{% block content %}
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'requestbox:index' %}">Home</a>
  </li>
</ul>


<table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">キャラ名</th>
        <th scope="col">作品タイトル</th>
        <th scope="col">#</th>
      </tr>
    </thead>

  <tbody id="mainlist">
    {% for req in req_list %}
    <tr>
      <th scope="row">{{ req.id }}</th>
      <td>{{ req.chara_name }}</td>
      <td>{{ req.title }}</td>
      <td><a href= "{% url "requestbox:delete" req.pk %}">削除</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}


{% endblock %}

requestbox/templates/requestbox/top.html
{% extends 'requestbox/base.html' %}

{% block content %}
<nav class="nav">
{% if user.is_superuser %}
<a class="nav-link" href="{% url 'requestbox:mypage' %}" >Mypage</a>
{% endif %}
</nav>
<h2> Top page </h2>
<p>
  ここでイラストのリクエストを受け付けています。<br>
  個人的なイラストリクエストでは無いですごめんなさい。<br>
</p>
<a class="nav-link" href="{% url 'requestbox:req' %}">
<button type="button" class="btn btn-dark">リクエストはここから</button>
</a>
{% endblock %}